# Generated by Django 5.0.4 on 2025-05-01 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('urlToImage', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('query', models.CharField(blank=True, max_length=100, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('everything', 'Everything'), ('top-headlines', 'Top Headlines')], default='everything', max_length=20)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('endpoint', 'query', 'language', 'country', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsCache.newsarticle')),
            ],
            options={
                'verbose_name': 'Favorite News',
                'verbose_name_plural': 'Favorite News',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
