# Generated by Django 5.0.4 on 2025-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsCache', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newscache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='newscache',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newscache',
            name='endpoint',
            field=models.CharField(choices=[('everything', 'Everything'), ('top-headlines', 'Top Headlines')], default='everything', max_length=20),
        ),
        migrations.AlterField(
            model_name='newscache',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='newscache',
            unique_together={('endpoint', 'query', 'language', 'country', 'category')},
        ),
    ]
