# Generated by Django 5.0.4 on 2025-05-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsCache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
